name: "Python CI"

on:
 push:
  branches: 
   - main
   - production

jobs:
 build:

   runs-on: ubuntu-latest

   steps:
   - name: Checkout Code
     uses: actions/setup-python@v4

   - name: Setup Python
     uses: actions/setup-python@v4
     with:
       python-sersion: "3.10"
   
   - name: Install Dependencies
     run: 
      python -m pip install --upgrade pip
      pip install -t requirnment.txt

   - name: Run Tests
     run:
      pytest 
      


    
