name: "Python CI"

on:
 push:
  branches: 
   - main
   - production

jobs:
 build:

   runs-on: ubuntu-latest

   steps:
   - name: Checkout Code
     uses: actions/checkout@v3

   - name: Setup Python
     uses: actions/setup-python@v3
     with:
       python-sersion: "3.10"
   
   - name: install dependencies
     run:
       python -m pip install --upgrade pip && pip install -r requirements.txt

   - name: Run Tests
     run:
      pytest 
      


    
